-- MySQL Script generated by MySQL Workbench
-- Wed Nov 29 20:15:23 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema quinoa
-- -----------------------------------------------------
-- data model for HYF final project

-- -----------------------------------------------------
-- Schema quinoa
--
-- data model for HYF final project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quinoa` DEFAULT CHARACTER SET utf8mb4 ;
USE `quinoa` ;

-- -----------------------------------------------------
-- Table `quinoa`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quinoa`.`categories` (
  `category_id` INT UNSIGNED NOT NULL,
  `category_name` VARCHAR(99) NULL,
  `quantity` INT UNSIGNED NOT NULL DEFAULT 1,
  `measurement_unit` VARCHAR(45) NULL,
  `water_consumption` INT UNSIGNED NULL DEFAULT 0,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quinoa`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quinoa`.`tags` (
  `tag_id` INT UNSIGNED NOT NULL,
  `tag_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tag_id`),
  UNIQUE INDEX `tag_name_UNIQUE` (`tag_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quinoa`.`categories_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quinoa`.`categories_tags` (
  `category_id` INT UNSIGNED NOT NULL,
  `tag_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`category_id`, `tag_id`),
  INDEX `tag_id_idx` (`tag_id` ASC),
  CONSTRAINT `category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `quinoa`.`categories` (`category_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `tag_id`
    FOREIGN KEY (`tag_id`)
    REFERENCES `quinoa`.`tags` (`tag_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;